# Mostly inspired by the .eslintrc that FB uses for React

parser: babel-eslint

extends:
  - eslint:recommended

plugins:
  - react

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true

globals:
  __dirname: true,
  __DEVTOOLS__: true,
  __DEVELOPMENT__: true,
  module: true,
  exports: true,
  require: true,
  process: true,

  # For Testing
  describe: true,
  it: true,
  beforeEach: true,
  afterEach: true,
  sinon: true,
  before: true,
  after: true,
  global: true


# We're stricter than the default config, mostly. We'll override a few rules and
# then enable some React specific ones.
rules:
  arrow-parens: [2, always]
  accessor-pairs: 0
  brace-style: [2, 1tbs]
  comma-dangle: [2, never]
  consistent-return: 2
  dot-location: [2, property]
  dot-notation: 2
  eol-last: 2
  indent: [2, 2, {SwitchCase: 1}]
  no-bitwise: 0
  no-dupe-class-members: 2
  no-multi-spaces: 2
  no-shadow: 2
  no-unused-vars: [2, {args: none}]
  padded-blocks: [2, never]
  quotes: [2, single, avoid-escape]
  semi: [2, always]
  keyword-spacing: 2
  spaced-comment: [2, always, {block: {exceptions: ["*"]}}]
  space-before-blocks: 2
  space-before-function-paren: [2, never]
  space-in-parens: [2, never]
  space-infix-ops: 2
  strict: [2, global]
  no-constant-condition: [2, {checkLoops: false}]
  prefer-const: [2, {destructuring: all, ignoreReadBeforeAssign: true}]
  no-var: 2

  # For testing
  no-unused-expressions: 0

  # JSX
  # Our transforms set this automatically
  react/display-name: 0
  react/jsx-boolean-value: [2, always]
  react/jsx-no-undef: 2
  # We don't care to do this
  react/jsx-sort-prop-types: 0
  react/jsx-sort-props: 0
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  # It's easier to test some things this way
  react/no-did-mount-set-state: 0
  react/no-did-update-set-state: 0
  # We define multiple components in test files
  react/no-multi-comp: 0
  react/no-unknown-property: 2
  # This isn't useful in our test code
  react/prop-types: 0
  react/react-in-jsx-scope: 2
  react/self-closing-comp: 2
  # We don't care to do this
  react/sort-comp: 0
  react/jsx-wrap-multilines: [2, {declaration: false, assignment: false}]
