# Mostly inspired by the .eslintrc that FB uses for React

parser: babel-eslint

extends:
  - eslint:recommended
  - prettier

plugins:
  - react
  - prettier

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true

globals:
  __dirname: true,
  __DEVTOOLS__: true,
  __DEVELOPMENT__: true,
  __TEST__: true,
  module: true,
  exports: true,
  require: true,
  process: true

rules:
  accessor-pairs: off
  brace-style: [error, 1tbs]
  comma-dangle: [error, never]
  consistent-return: error
  dot-location: [error, property]
  dot-notation: error
  eol-last: error
  eqeqeq: [error, always, { null: ignore }]
  keyword-spacing: error
  no-bitwise: off
  no-constant-condition: [error, { checkLoops: false }]
  no-dupe-class-members: error
  no-multi-spaces: error
  no-shadow: error
  no-unused-expressions: error
  no-unused-vars: [error, { args: none }]
  no-var: error
  padded-blocks: [error, never]
  prefer-const: [error, { destructuring: all, ignoreReadBeforeAssign: true }]
  prettier/prettier: [error, { singleQuote: true, trailingComma: none, printWidth: 120 }]
  quotes: [error, single, avoid-escape]
  semi: [error, always]
  space-before-blocks: error
  space-before-function-paren: [error, never]
  space-in-parens: [error, never]
  space-infix-ops: error
  spaced-comment: [error, always, { block: { exceptions: ["*"] } }]
  strict: [error, global]

  # JSX
  # Our transforms set this automatically
  react/display-name: off
  react/jsx-boolean-value: [error, always]
  react/jsx-no-undef: error
  react/jsx-sort-prop-types: off
  react/jsx-sort-props: off
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-wrap-multilines: [error, { declaration: false, assignment: false }]
  react/no-did-mount-set-state: off
  react/no-did-update-set-state: off
  react/no-multi-comp: off
  react/no-unknown-property: error
  react/prop-types: off
  react/react-in-jsx-scope: error
  react/self-closing-comp: error
  react/sort-comp: off

overrides:
- files:
    - "src/components/**/__tests__/*-test.js?(x)"
  globals:
    describe: true,
    it: true,
    beforeEach: true,
    afterEach: true,
    sinon: true,
    before: true,
    after: true,
    process: true,
    global: true
  rules:
    no-unused-expressions: 0
